import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="font-Poppins font-medium h-full relative">
      <Head>
        <title>Nick Douglas | Frontend Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="w-full absolute top-0 left-0 p-2">
        <h1 className='text-2xl font-semibold tracking-tighter'>Nick Douglas.</h1>
      </nav>

      <main className="container px-4 h-full">
        <header className="h-screen flex justify-center flex-col">
          <h2 className="text-[80px] leading-[90px] mb-6">A passionate frontend web developer building great things for the web.</h2>
          <h3 className="text-2xl font-light text-gray-700 leading-[46px] w-3/4">Senior Freelance Frontend Developer</h3>
        </header>
      </main>
    </div>
  )
}

export default Home
